server:
  port: 8080


spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/reelse"
    username: root
    password: "09122005Vi@"

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


jwt:
    signerKey: "y,!+kLi&>Vw+?iUTHL5=69D+]&vVqg-S*9CYml&18}7TR.d,6}*M1}<S(#.z84}D"